Feature/path service portfolio
PEM-Humboldt/biotablero-backend pull request #360
Opened 2023-07-18 17:00 UTC by hacheG

2023-07-19 14:12 UTC, cazapatamar approved these changes

2023-07-19 15:22 UTC, erikasv commented on services/portfolios_ca/src/util/logger.ts
> +const currentFileUrl = fileURLToPath(new URL(import.meta.url));
:+1:

2023-07-24 13:11 UTC, erikasv requested changes
The solution works well, but the name of the variables are no w confusing, please use appropriate names

2023-07-25 14:13 UTC, erikasv requested changes

2023-07-25 14:13 UTC, erikasv commented on services/portfolios_ca/src/util/logger.ts
> +const currentFolder = path.dirname(absolutePathMain);
this variable name is also wrong

2023-07-26 13:55 UTC, erikasv approved these changes

2023-07-26 16:06 UTC, merged