Update node backend main service
PEM-Humboldt/biotablero-backend pull request #374
Opened 2023-08-29 15:07 UTC by cazapatamar

2023-08-30 01:23 UTC, erikasv requested changes
persistence/project needs change for an error

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/routes/protected_areas.js
> +      const error = { code: 400, message: 'areaType and areaId required' };
change this error

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/routes/protected_areas.js
> +      const error = { code: 400, message: 'areaType, areaId and seType required' };
change this error

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/service/project.js
> +      throw new RestifyErrors.NotFoundError(`Some of ${groupProps} are not project properties`);
this should be a bad request

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/service/project.js
> +      throw new RestifyErrors.NotFoundError('Missing or invalid project id');
bad request too

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/service/project.js
> +      throw new RestifyErrors.NotFoundError('Invalid project id');
bad request

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/service/project.js
> +      throw new RestifyErrors.NotFoundError('Invalid project id');
bad request

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/service/project.js
> +      throw new RestifyErrors.NotFoundError('Invalid project id');
bad reqeuest

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/service/project_strategy.js
> +      throw new RestifyErrors.NotFoundError('Invalid project id');
bad request

2023-08-30 01:23 UTC, erikasv commented on services/backend/src/service/project_strategy.js
> +      throw new RestifyErrors.NotFoundError('Invalid project id');
bad request

2023-08-30 21:59 UTC, erikasv requested changes

2023-08-30 21:59 UTC, erikasv commented on services/backend/src/persistence/models/util/events.js
> +    throw new RestifyErrors.NotFoundError(
bad request

2023-08-30 23:33 UTC, cazapatamar commented on services/backend/src/persistence/models/util/events.js
> +    throw new RestifyErrors.NotFoundError(
Fixed!

2023-08-31 15:13 UTC, cazapatamar commented on services/backend/src/service/project.js
> +      throw new RestifyErrors.NotFoundError('Invalid project id');
Fixed!

2023-08-31 15:30 UTC, ManuelStardust approved these changes
update works fine

2023-08-31 21:01 UTC, erikasv approved these changes

2023-08-31 21:16 UTC, merged